version: '3.5'

services:
  xpra-server:
    image: xpra-server
    container_name: xpra-server-${SERVER_ID}-${HIP_USER}
    hostname: xpra-server-${SERVER_ID}-${HIP_USER}
    build:
      context: ./services
      dockerfile: server/Dockerfile
    volumes: 
      - x11-unix:/tmp/.X11-unix
    networks:
      - server
    ports:
      - 8080
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all       
    healthcheck:
      test: ["CMD", "curl", "-fks", "https://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  brainstorm:
    image: brainstorm
    #image: brainstorm:${BRAINSTORM_VERSION}
    container_name: brainstorm-${SERVER_ID}-${APP_ID}-${HIP_USER}
    hostname: brainstorm-${SERVER_ID}-${APP_ID}-${HIP_USER}
    build:
      context: ./services
      dockerfile: apps/brainstorm/Dockerfile
      #args:
        #BRAINSTORM_VERSION: ${BRAINSTORM_VERSION}
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - x11-unix:/tmp/.X11-unix
      - ./services/apps/brainstorm/run:/apps/brainstorm/run
    networks:
      - server
      - apps
    devices:
      - /dev/dri:/dev/dri
      - /dev/fuse:/dev/fuse
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all       
      - HIP_USER=${HIP_USER}
      - HIP_PASSWORD=${HIP_PASSWORD}
      - NEXTCLOUD_DOMAIN=${NEXTCLOUD_DOMAIN}
      - CARD=${CARD}
    healthcheck:
      test: ["CMD", "/apps/brainstorm/scripts/process-healthcheck.sh", "brainstorm3.jar"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - xpra-server
    restart: on-failure
  vgl-base:
    image: vgl-base:${VIRTUALGL_VERSION}
    build:
      context: ./services
      dockerfile: base-images/vgl-base/Dockerfile
      args:
        VIRTUALGL_VERSION: ${VIRTUALGL_VERSION}
  nc-webdav:
    image: nc-webdav
    build:
      context: ./services
      dockerfile: base-images/nc-webdav/Dockerfile
  matlab-runtime:
    image: matlab-runtime:${MATLAB_RUNTIME_VERSION}_u${MATLAB_RUNTIME_UPDATE}
    build:
      context: ./services
      dockerfile: base-images/matlab-runtime/Dockerfile
      args:
        MATLAB_RUNTIME_VERSION: ${MATLAB_RUNTIME_VERSION}
        MATLAB_RUNTIME_UPDATE: ${MATLAB_RUNTIME_UPDATE}

volumes:
  x11-unix:

networks:
  server:
    driver: bridge
  apps:
    internal: true
    driver_opts:
      com.docker.network.driver.mtu: 1450
