version: '3.5'

services:
  xpra-server:
    image: xpra-server
    build:
      context: ./server
      args:
        VIRTUALGL_VERSION: 2.6.80
    volumes: 
      - x11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    networks:
      - server
    ports:
      - "8080:8080"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all       
    restart: unless-stopped
  brainstorm:
    image: brainstorm:210218
    build:
      context: ./apps/brainstorm
      args:
        VIRTUALGL_VERSION: 2.6.80
    volumes:
      - x11-unix:/tmp/.X11-unix
      - ./apps/brainstorm/run:/home/hip-user/apps/brainstorm/run
    networks:
      - server
      - apps
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all       
    restart: unless-stopped
  vgl-base:
    image: vgl-base
    build:
      context: ./base-images/vgl-base
      args:
        VIRTUALGL_VERSION: 2.6.80
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all       
  matlab-runtime:
    image: matlab-runtime:R2020a_u6
    build:
      context: ./base-images/matlab-runtime
      args:
        MATLAB_RUNTIME_VERSION: R2020a_u6

volumes:
  x11-unix:

networks:
  server:
    driver: bridge
  apps:
    internal: true
