version: '3.5'

services:
  xpra-server:
    image: xpra-server
    container_name: xpra-server-${SERVER_ID}-${NEXTCLOUD_USERNAME}
    hostname: xpra-server-${SERVER_ID}-${NEXTCLOUD_USERNAME}
    build:
      context: ./services
      dockerfile: server/Dockerfile
    volumes: 
      - x11-unix:/tmp/.X11-unix
    networks:
      - server
    ports:
      - ${SERVER_PORT}:8080
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all       
    healthcheck:
      test: ["CMD", "curl", "-fks", "https://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  brainstorm:
    image: brainstorm:210218
    container_name: brainstorm-${SERVER_ID}-${APP_ID}-${NEXTCLOUD_USERNAME}
    hostname: brainstorm-${SERVER_ID}-${APP_ID}-${NEXTCLOUD_USERNAME}
    build:
      context: ./services
      dockerfile: apps/brainstorm/Dockerfile
    volumes:
      - x11-unix:/tmp/.X11-unix
      - ./services/apps/brainstorm/run:/home/hip-user/apps/brainstorm/run
    networks:
      - server
      - apps
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all       
    healthcheck:
      test: ["CMD", "/home/hip-user/scripts/process_healthcheck.sh", "brainstorm3.jar"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - xpra-server
    restart: on-failure
  vgl-base:
    image: vgl-base:${VIRTUALGL_VERSION}
    build:
      context: ./services
      dockerfile: base-images/vgl-base/Dockerfile
      args:
        VIRTUALGL_VERSION: ${VIRTUALGL_VERSION}
  matlab-runtime:
    image: matlab-runtime:${MATLAB_RUNTIME_VERSION}
    build:
      context: ./services
      dockerfile: base-images/matlab-runtime/Dockerfile
      args:
        MATLAB_RUNTIME_VERSION: ${MATLAB_RUNTIME_VERSION}

volumes:
  x11-unix:

networks:
  server:
    driver: bridge
  apps:
    internal: true
