version: '3.4'

services:
  xpra-server:
    image: xpra-server
    build: ./server
    volumes: 
      - x11-unix:/tmp/.X11-unix
    networks:
      - server
    ports:
      - "8080:8080"
  matlab-runtime:
    image: matlab-runtime:R2020a_u6
    build:
      context: ./apps/matlab-runtime
      args:
        MATLAB_RUNTIME_VERSION: R2020a_u6
  brainstorm:
    image: brainstorm:210218
    build: ./apps/brainstorm
    volumes:
      - x11-unix:/tmp/.X11-unix
      - ./apps/brainstorm/run:/home/hip-user/apps/brainstorm/run
    networks:
      - server
      - apps
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]

volumes:
  x11-unix:

networks:
  server:
    driver: bridge
  apps:
    internal: true
