version: '3.5'

services:
  xpra-server:
    image: xpra-server
    build:
      context: ./services
      dockerfile: server/Dockerfile
    volumes: 
      - x11-unix:/tmp/.X11-unix
    networks:
      - server
    ports:
      - "8080:8080"
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all       
    restart: unless-stopped
  brainstorm:
    image: brainstorm:210218
    build:
      context: ./services
      dockerfile: apps/brainstorm/Dockerfile
    volumes:
      - x11-unix:/tmp/.X11-unix
      - ./services/apps/brainstorm/run:/home/hip-user/apps/brainstorm/run
    networks:
      - server
      - apps
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all       
    restart: unless-stopped
  vgl-base:
    image: vgl-base:${VIRTUALGL_VERSION}
    build:
      context: ./services
      dockerfile: base-images/vgl-base/Dockerfile
      args:
        VIRTUALGL_VERSION: ${VIRTUALGL_VERSION}
  matlab-runtime:
    image: matlab-runtime:${MATLAB_RUNTIME_VERSION}
    build:
      context: ./services
      dockerfile: base-images/matlab-runtime/Dockerfile
      args:
        MATLAB_RUNTIME_VERSION: ${MATLAB_RUNTIME_VERSION}

volumes:
  x11-unix:

networks:
  server:
    driver: bridge
  apps:
    internal: true
