FROM registry.hbp.link/hip/app-in-browser/xpra-server:master

COPY background.png /usr/share/backgrounds/default.png
RUN ln -sf /usr/share/backgrounds/default.png /usr/share/backgrounds/ubuntu-default-greyscale-wallpaper.png