name: gitlab-sync
on: push
  branches:
    - master
    - dev
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ secrets.SOURCE_GITHUB }}
          source_branch: ${GITHUB_REF##*/}
          destination_repo: ${{ secrets.TARGET_GITLAB }}
          destination_branch: ${GITHUB_REF##*/}
