on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "HIP-infrastructure/app-in-browser"
          source_branch: "master"
          destination_repo: ${{ secrets.TARGET_GITLAB }}
          destination_branch: "master"
